////////////////////////////////////////////////////////
// Version.h

// Version file auto generated by IncBuild.
// Abin (abinn32@163.com)
// 2015-01-25
////////////////////////////////////////////////////////

#ifndef __VERSION_H__
#define __VERSION_H__

#define APP_VERSION_MAJOR	(1) // Major version, can be modified.
#define APP_VERSION_MINOR	(1) // Minor version, can be modified.
#define APP_VERSION_BUILD	(4) // Build number, will be auto incremented by IncBuild

#endif // __VERSION_H__
