////////////////////////////////////////////////////////
// Version.cpp

// Version file auto generated by IncBuild.
// Abin (abinn32@163.com)
// 2015-01-25
////////////////////////////////////////////////////////

#include "stdafx.h"
#include "Version.h"

int AfxCompareVersion(int nMajor, int nMinor, int nBuild)
{
	if (APP_VERSION_MAJOR > nMajor)
		return -1;

	if (APP_VERSION_MAJOR < nMajor)
		return 1;

	if (APP_VERSION_MINOR > nMinor)
		return -1;

	if (APP_VERSION_MINOR < nMinor)
		return 1;

	if (APP_VERSION_BUILD > nBuild)
		return -1;

	if (APP_VERSION_BUILD < nBuild)
		return 1;

	return 0;
}

CString AfxGetVersion(BOOL bShowBuild)
{
	CString sVersion;

	if (bShowBuild)
		sVersion.Format(_T("%d.%02d.%04d"), APP_VERSION_MAJOR, APP_VERSION_MINOR, APP_VERSION_BUILD);
	else
		sVersion.Format(_T("%d.%02d"), APP_VERSION_MAJOR, APP_VERSION_MINOR);

	return sVersion;
}
